# Generated by Django 3.2.6 on 2021-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
