# Generated by Django 3.2.6 on 2021-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210811_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sub', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
