# Generated by Django 3.2.6 on 2021-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mimage',
            field=models.ImageField(default='alt.png', upload_to='movies'),
        ),
    ]
