# Generated by Django 3.2.6 on 2021-08-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_movies_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='video',
        ),
    ]
